export const projects = [
  {
    id: 'internet-buddy',
    name: 'Internet Buddy',
    tagline: 'Smart Internet Control for Schools & Parents',
    description:
      'Internet Buddy is een applicatie ontwikkeld in opdracht van de Belgische overkoepelende schoolgemeenschap. Het systeem geeft ouders en scholen volledige controle over het internetgebruik van leerlingen via geofence-technologie en agenda-planning.',
    features: [
      'Internet op afstand aan/uitzetten',
      'Agenda-planning voor internetgebruik',
      'Geofence technologie',
      'Automatisch uitschakelen nabij school',
      'Remote beheer voor ouders & scholen',
      'Centraal cloud dashboard',
    ],
    tech: ['Mobile Apps', 'Geolocation', 'Cloud Backend', 'Device Management'],
    color: '#4F8EF7',
    emoji: '📡',
    video: '/internet-buddy-demo.mp4',
    url: 'https://www.vysionapps.io/home',
  },
  {
    id: 'restaurant-pos',
    name: 'Restaurant POS System',
    tagline: 'Complete Horeca Kassasysteem',
    description:
      'Een uitgebreid horeca kassasysteem met realtime bestellingen en uitgebreide rapportage. Ontwikkeld voor restaurants die een complete digitale oplossing nodig hebben voor hun dagelijkse werking.',
    features: [
      'Volledig kassasysteem',
      'Keuken display systeem',
      'Realtime bestellingen',
      'Uitgebreide rapportage',
      'Restaurant workflow beheer',
      'Gebouwd in 9 talen',
    ],
    tech: ['Realtime Database', 'Cloud Backend', 'Dashboard', 'Restaurant Software'],
    color: '#7C6EF0',
    emoji: '🍽️',
    video: '/restaurant-pos-demo.mp4',
    url: 'https://www.vysionhoreca.com/kassa',
    github: 'https://github.com/rudiaerden19-blip/vysionhoreca-website',
  },
  {
    id: 'restaurant-ordering',
    name: 'Horeca Online Bestelplatform',
    tagline: 'Bestellen via WhatsApp & Web',
    description:
      'Een online bestelplatform voor restaurants waarbij klanten rechtstreeks kunnen bestellen via WhatsApp. Het platform biedt restaurants een eenvoudige manier om online bestellingen te beheren met realtime updates.',
    features: [
      'Bestellen via WhatsApp',
      'iOS en Android app',
      'Realtime order tracking',
      'Keuken scherm integratie',
      'Online betalingen',
      'Realtime updates & notificaties',
    ],
    tech: ['Supabase Realtime', 'Web Applications', 'Cloud Backend', 'Messaging API'],
    url: 'https://www.vysionhoreca.com',
    github: 'https://github.com/rudiaerden19-blip/vysionhoreca-website',
    color: '#22D3A5',
    emoji: '📱',
    video: '/restaurant-ordering-demo.mp4',
  },
  {
    id: 'voxapp',
    name: 'VoxApp',
    tagline: 'AI Voice Agent Platform',
    description:
      'VoxApp is een AI-gestuurde receptioniste voor alle bedrijven. Het platform verwerkt inkomende gesprekken automatisch en geeft klanten direct het juiste antwoord — 24/7, zonder menselijke tussenkomst.',
    features: [
      'AI receptioniste',
      'Spraakherkenning 9 talen',
      'Text-to-speech',
      'Realtime gespreksverwerking',
      'Enterprise logging & monitoring',
      'Multi-tenant architectuur',
    ],
    tech: ['Vapi AI', 'Deepgram STT', 'ElevenLabs TTS', 'Supabase', 'Next.js'],
    color: '#F7804F',
    emoji: '🎙️',
    video: '/voxapp-demo.mp4',
  },
  {
    id: 'safelink',
    name: 'SafeLink',
    tagline: 'Veiligheidsapp voor noodsituaties',
    description:
      'SafeLink is een veiligheidsapp die mensen helpt snel hulp te vinden en noodsituaties te melden. De app biedt directe toegang tot hulpdiensten, live locatie delen en persoonlijke ondersteuning — volledig offline beschikbaar.',
    features: [
      'SOS noodknop',
      'Live locatie delen',
      'Directe toegang tot hulpdiensten',
      'Hulpvragenlijsten',
      'Forum voor ondersteuning',
      'Persoonlijk dagboek',
      '22 talen ondersteund',
      'Offline-first architectuur',
    ],
    tech: ['React Native', 'Expo', 'Supabase', 'i18n', 'Offline Storage'],
    color: '#F7804F',
    emoji: '🛡️',
    video: '/safelink-demo.mp4',
  },
]

export const services = [
  {
    id: 'saas',
    title: 'SaaS Development',
    description: 'Ontwikkeling van complete SaaS platforms met realtime backend systemen, dashboards en gebruikersbeheer.',
    icon: '☁️',
    image: '/services/saas.png',
    features: ['Realtime systemen', 'Multi-tenant architectuur', 'Subscription billing', 'Admin dashboards'],
  },
  {
    id: 'web',
    title: 'Web Applications',
    description: 'Dashboards, bedrijfssoftware en interne tools op maat gebouwd voor jouw processen.',
    icon: '🖥️',
    image: '/services/web.png',
    features: ['React & Next.js', 'Database architectuur', 'REST & realtime API', 'Performance optimalisatie'],
  },
  {
    id: 'mobile',
    title: 'Mobile Applications',
    description: 'Mobiele apps voor iOS en Android met native performance en moderne UI.',
    icon: '📱',
    image: '/services/mobile.png',
    features: ['React Native / Expo', 'iOS & Android', 'Offline-first', 'Push notificaties'],
  },
  {
    id: 'websites',
    title: 'Custom Websites',
    description: 'Professionele maatwerk websites voor bedrijven, organisaties en startups.',
    icon: '🌐',
    image: '/services/websites.png',
    features: ['Next.js & Tailwind', 'SEO geoptimaliseerd', 'CMS integratie', 'Snelle laadtijden'],
  },
  {
    id: 'mvp',
    title: 'Startup MVP Development',
    description: 'Van idee naar werkend softwareproduct binnen enkele maanden — klaar voor eerste gebruikers.',
    icon: '🚀',
    image: '/services/mvp.png',
    features: ['Snelle oplevering', 'Schaalbare basis', 'Iteratieve aanpak', 'Van concept tot lancering'],
  },
]

export const technologies = [
  { name: 'Next.js', icon: '▲', image: '/tech/nextjs.png', category: 'Framework' },
  { name: 'TypeScript', icon: 'TS', image: '/tech/typescript.png', category: 'Language' },
  { name: 'JavaScript', icon: 'JS', image: '/tech/javascript.png', category: 'Language' },
  { name: 'React Native', icon: '⚛', image: '/tech/reactnative.png', category: 'Mobile' },
  { name: 'Tailwind CSS', icon: '🎨', image: '/tech/tailwind.png', category: 'Styling' },
  { name: 'Supabase', icon: '⚡', image: '/tech/supabase.png', category: 'Backend' },
  { name: 'Firebase', icon: '🔥', image: '/tech/firebase.png', category: 'Backend' },
  { name: 'Vercel', icon: '▲', image: '/tech/vercel.png', category: 'Deployment' },
  { name: 'GitHub', icon: '🐙', image: '/tech/github.png', category: 'Version Control' },
  { name: 'Framer Motion', icon: '✦', image: '/tech/framer.png', category: 'Animation' },
  { name: 'SaaS Architecture', icon: '☁️', image: '/tech/saas.png', category: 'Architecture' },
  { name: 'Cursor AI', icon: '◎', category: 'Tools' },
]
